export const destinations = [
            {
                  id: 1,
                  name: "NYK",
                  value: 85,
                  distance: 8900,
                  danger: 25,
            },
            {
                  id: 2,
                  name: "LAX",
                  value: 78,
                  distance: 8200,
                  danger: 20,
            },
            {
                  id: 3,
                  name: "SIN",
                  value: 92,
                  distance: 6500,
                  danger: 30,
            },
            {
                  id: 4,
                  name: "RTD",
                  value: 88,
                  distance: 10200,
                  danger: 40,
            },
            {
                  id: 5,
                  name: "SHA",
                  value: 90,
                  distance: 7000,
                  danger: 35,
            },
            {
                  id: 6,
                  name: "SYD",
                  value: 75,
                  distance: 3800,
                  danger: 15,
            },
            {
                  id: 7,
                  name: "DXB",
                  value: 85,
                  distance: 8100,
                  danger: 45,
            },
            {
                  id: 8,
                  name: "CPT",
                  value: 65,
                  distance: 4000,
                  danger: 20,
            },
            {
                  id: 9,
                  name: "TYO",
                  value: 88,
                  distance: 7500,
                  danger: 30,
            },
            {
                  id: 10,
                  name: "HAM",
                  value: 82,
                  distance: 10300,
                  danger: 40,
            },
            {
                  id: 11,
                  name: "BUE",
                  value: 50,
                  distance: 2900,
                  danger: 10,
            },
            {
                  id: 12,
                  name: "RIO",
                  value: 60,
                  distance: 4500,
                  danger: 15,
            },
            {
                  id: 13,
                  name: "PCY",
                  value: 70,
                  distance: 7900,
                  danger: 25,
            },
            {
                  id: 14,
                  name: "MUM",
                  value: 80,
                  distance: 6900,
                  danger: 35,
            },
            {
                  id: 15,
                  name: "HKG",
                  value: 85,
                  distance: 6800,
                  danger: 30,
            },
            {
                  id: 16,
                  name: "AKL",
                  value: 68,
                  distance: 4100,
                  danger: 12,
            },
            {
                  id: 17,
                  name: "MNL",
                  value: 76,
                  distance: 6300,
                  danger: 28,
            },
            {
                  id: 18,
                  name: "POM",
                  value: 62,
                  distance: 4500,
                  danger: 18,
            },
            {
                  id: 19,
                  name: "LIS",
                  value: 80,
                  distance: 9800,
                  danger: 38,
            },
            {
                  id: 20,
                  name: "IST",
                  value: 85,
                  distance: 8500,
                  danger: 45,
            },
            {
                  id: 21,
                  name: "SFO",
                  value: 75,
                  distance: 8100,
                  danger: 22,
            },
            {
                  id: 22,
                  name: "VAL",
                  value: 58,
                  distance: 2800,
                  danger: 12,
            },
            {
                  id: 23,
                  name: "MEL",
                  value: 73,
                  distance: 3900,
                  danger: 14,
            },
            {
                  id: 24,
                  name: "HFX",
                  value: 70,
                  distance: 9000,
                  danger: 30,
            },
            {
                  id: 25,
                  name: "KHI",
                  value: 78,
                  distance: 7000,
                  danger: 37,
            },
];

export default destinations;